services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - group-service
  user-service:
    image: user-service
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "1000:8080"
  group-service:
    image: group-service
    build:
      context: .
      dockerfile: GroupService/Dockerfile
    ports:
      - "2000:8080"