services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - group-service
      - expense-service
  user-service:
    image: user-service
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "1000:8080"
  group-service:
    image: group-service
    build:
      context: .
      dockerfile: GroupService/Dockerfile
    ports:
      - "2000:8080"
  expense-service:
    image: expense-service
    build:
      context: .
      dockerfile: ExpenseService/Dockerfile
    ports:
      - "3000:8080"
  rabbitmq:
    user: "999"
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - '5672:5672'
      - '15672:15672'
