services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: deployable/Gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - group-service
      - expense-service
      - auth-service
  user-service:
    image: user-service
    build:
      context: .
      dockerfile: deployable/UserService/Dockerfile
    ports:
      - "1000:8080"
    environment:
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VIRTUALHOST=${RABBITMQ_VIRTUALHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
          condition: service_healthy
  auth-service:
    image: auth-service
    build:
      context: .
      dockerfile: deployable/AuthService/Dockerfile
    ports:
      - "1500:8080"
    depends_on: 
      - user-service
  group-service:
    image: group-service
    build:
      context: .
      dockerfile: deployable/GroupService/Dockerfile
    ports:
      - "2000:8080"
    environment:
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VIRTUALHOST=${RABBITMQ_VIRTUALHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
  expense-service:
    image: expense-service
    build:
      context: .
      dockerfile: deployable/ExpenseService/Dockerfile
    ports:
      - "3000:8080"
    environment:
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VIRTUALHOST=${RABBITMQ_VIRTUALHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    user: "999"
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VIRTUALHOST=${RABBITMQ_VIRTUALHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
  user-repo:
    image: user-repo
    build:
      context: .
      dockerfile: deployable/UserRepository/Dockerfile
    ports:
      - "4000:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VIRTUALHOST=${RABBITMQ_VIRTUALHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
  group-repo:
    image: group-repo
    build:
      context: .
      dockerfile: deployable/GroupRepository/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - deployable/GroupRepository/appsettings.development.json
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VIRTUALHOST=${RABBITMQ_VIRTUALHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  expense-repo:
    image: expense-repo
    build:
      context: .
      dockerfile: deployable/ExpenseRepository/Dockerfile
    ports:
      - "6000:8080"
    environment:
      - RABBITMQ_HOSTNAME=${RABBITMQ_HOSTNAME}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VIRTUALHOST=${RABBITMQ_VIRTUALHOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    depends_on:
      rabbitmq:
        condition: service_healthy
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341" 
      - "5342:80" 
    environment:
      ACCEPT_EULA: Y
