services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: deployable/Gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - group-service
      - expense-service
  user-service:
    image: user-service
    build:
      context: .
      dockerfile: deployable/UserService/Dockerfile
    ports:
      - "1000:8080"
  group-service:
    image: group-service
    build:
      context: .
      dockerfile: deployable/GroupService/Dockerfile
    ports:
      - "2000:8080"
  expense-service:
    image: expense-service
    build:
      context: .
      dockerfile: deployable/ExpenseService/Dockerfile
    ports:
      - "3000:8080"
  rabbitmq:
    user: "999"
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - '5672:5672'
      - '15672:15672'
  user-repo:
    image: user-repo
    build:
      context: .
      dockerfile: deployable/UserRepository/Dockerfile
    ports:
      - "4000:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
  group-repo:
    image: group-repo
    build:
      context: .
      dockerfile: deployable/GroupRepository/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - deployable/GroupRepository/appsettings.development.json
    depends_on:
      rabbitmq:
        condition: service_healthy
  expense-repo:
    image: expense-repo
    build:
      context: .
      dockerfile: deployable/ExpenseRepository/Dockerfile
    ports:
      - "6000:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
