services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
        - "8080:8080"
    depends_on:
      - user-service

  user-service:
    image: user-service
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
        - "1000:8080"